function(run_dict_test)
  include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../dict.cmake")
  dict(test_dict NEW)
  dict(test_dict SET KEY "key" VALUE "value")
  dict(test_dict GET _val KEY "key" VALUE "value")
  message(STATUS "test_dict GET result -- 'key': '${_val}'")
  dict(test_dict SET KEY "key.test" VALUE "value1" "value2")
  dict(test_dict GET _val KEY "key.test")
  message(STATUS "test_dict GET result -- 'key.test': '${_val}'")
  dict(test_dict SET KEY "key test" VALUE "value1 value2")
  dict(test_dict GET _val KEY "key test")
  message(STATUS "test_dict GET result -- 'key test': '${_val}'")
  return()
  dict(dict1 NEW)
  dict(dict1 SET KEY "jsonval" VALUE "${test_dict}")
  message(STATUS "test_dict: '${test_dict}', dict1: '${dict1}'")
  foreach(_v ${_val})
    message(STATUS "test_dict: '${_v}'")
  endforeach()
  message(STATUS "test_dict GET result -- '_val': '${_val}'")
  return()
endfunction()